# this is the start of my terminal rice
# font_family JetBrainsMonoNL.tff


# BEGIN_KITTY_FONTS
font_family      family='JetBrains Mono NL' style=Medium
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

#Cursor Customization
# cursor #0cc087
# cursor_text_color #0cc087
cursor_shape underline
#End Cursor Customization


# Color Scheming
# foreground #A9B1DC
# background #1A1b2c
background_opacity .8
#End Color Scheming


# zsh launch
 shell /usr/bin/zsh


confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Snazzy
include current-theme.conf
# END_KITTY_THEME
